name: Update Star Data

on:
  schedule:
    - cron: '0 0 * * *' # Runs nightly at midnight
  workflow_dispatch:

jobs:
  update-star-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv loguru rich tenacity pydantic typer

    - name: Fetch star data
      run: |
        python ./.github/scripts/fetch_star_data.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add data/star-data.json
        git commit -m 'Update star data'
        git push
